### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by yepidoodles** [TheoKah/CarrotShop#1]
http://www.codesend.com/view/dabd2a5f434ef13b457221fc4929602a/

**Comment by TheoKah** [comment]
This was a problem caused by my build environment. Thank you for pointing this out.
The build here is now correct: https://github.com/TheoKah/CarrotShop/releases/tag/1.2

**Comment by TheoKah** [comment]
Also up to date here: https://ore.spongepowered.org/Carrot/CarrotShop

**Comment by yepidoodles** [comment]
That seems to have fixed it :)
