### ISSUE TITLE
Not working after restart.

### ISSUE THREAD

**Issue by ManningSquared** [TheoKah/CarrotShop#11]
I just filled a shop with your sign plugin, taking an hour of work, and I restart the server, and moded items do not working anymore. We tested everything and it all worked beforehand.

What do I do?

Thanks,

ManningSquared.

**Comment by yepidoodles** [comment]
Which versions are you using? (MC, CarrotShop, Sponge, which mods you used in your shops)

**Comment by ManningSquared** [comment]
Sponge, Buildcraft, Thermal Series, and ic2

**Comment by TheoKah** [comment]
Do you see errors in console during the startup phase.
Do you loose all shops or only the ones with modded items?

**Comment by ManningSquared** [comment]
Only the modded ones are lost, but now some of the modded ones are working? 

No errors in console.


Thanks for the help,

Manning.

**Comment by TheoKah** [comment]
Can you list me the items/mods that are not saved correctly?

When you say 'not working' you mean the sign turn red and do not recognise the items in the chest? Or the sign has no color and is not a shop at all?

**Comment by ManningSquared** [comment]
It's iBuy, and they don't even turn red, they are blue, you just can't use them, like you can't right OR left click on them. Here are the ones that are not working.
![2017-07-27_15 04 33](https://user-images.githubusercontent.com/23730718/28694355-e9c5a59e-72dd-11e7-9e58-1c3bc7d7899c.png)
![2017-07-27_15 04 42](https://user-images.githubusercontent.com/23730718/28694357-eb30f49c-72dd-11e7-8358-bfea8eb0fba3.png)

**Comment by TheoKah** [comment]
It is having a hard time with containers... I'll have a look

**Comment by TheoKah** [comment]
Sorry for late answer about this one.
I changed something in v1.16 that should fix this problem
