### ISSUE TITLE
Others can open CarrotShop chests

### ISSUE THREAD

**Issue by ejektaflex** [TheoKah/CarrotShop#13]
Others can open and close my CarrotShop chests, as well as insert and remove items from them (But they still cannot break the sign.)

I'm on SpongeForge 1.12-2443-7.0.0-BETA-2498. I've tested this with only Forge, Sponge and CarrotShop 1.9 loaded.

**Comment by TheoKah** [comment]
This plugin is not a protection plugin. I only prevent the destruction of the chest by non-owner.

If I want to prevent people opening the chest, then I will need to protect the area around it to prevent others from using hoppers or other modded item to steal from it.

You want to use a proper protection plugin for this.
