### ISSUE TITLE
Cannot remove sign

### ISSUE THREAD

**Issue by japtic** [TheoKah/CarrotShop#14]
I have created server shop sign [iBuy] and i want to remove it but its going away.
removed with gun powder or worldedit  make it visually gone but if I place sign or block where it was, it is still there. trying to break block will say dirt for 1 coin? and block will not break unless gunpowder or worldedit. server did restart but its still there.
edit: gunpowder was from voxel i think?

**Comment by TheoKah** [comment]
Make sure you have the admin perm.
Also, if you are in creative, either switch to survival or use bedrock to destroy the sign.

**Comment by japtic** [comment]
oh sorry bedrock works thank you
