### ISSUE TITLE
Offhand infinite money glitch

### ISSUE THREAD

**Issue by japtic** [TheoKah/CarrotShop#15]
players are able to "sell" without losing the item they are holding on the off-hand.
Place Diamond on the off hand, keep right click the sign and sign will pay you money even if the diamond on the off hand will not get consumed.

**Comment by TheoKah** [comment]
Thank you for pointing that out. I'll see if I can hotfix that tonight.

Now that you mention that, is it the same with armor slots?

**Comment by TheoKah** [comment]
Fixed: https://github.com/TheoKah/CarrotShop/releases/tag/1.10
