### ISSUE TITLE
Sign dupe

### ISSUE THREAD

**Issue by Dpa1991** [TheoKah/CarrotShop#17]
If you create a shop and get a friend to break the block the shop sign rests on, it will drop a sign and leave the shop sign up. Simply have your friend place another block and break it again and repeat.

Not that serious, but felt worth reporting. Maybe have the shop plugin protect both the sign & block it rests on

**Comment by TheoKah** [comment]
What version of sponge are you using?

I'll fix that in a few hours

**Comment by Dpa1991** [comment]
I haven't updated in a while, I just got done dealing with Irma - I am on 2281-5.2.0-2597. I can update & test further, that thought didnt cross my mind.

**Comment by TheoKah** [comment]
I'm able to reproduce it. Protecting the supporting block prevents the sign drop. I should be able to publish the fix by the end of the week end

**Comment by TheoKah** [comment]
Fixed: https://github.com/TheoKah/CarrotShop/releases/tag/1.13
