### ISSUE TITLE
Shop not saving on restart [Fixed]

### ISSUE THREAD

**Issue by ratquaza** [TheoKah/CarrotShop#18]
After using the new latest version with multicurrency support, the signs do not save after a server stop.[ This error comes up whenever I create a sign shop](https://pastebin.com/rMgW4X8B). I've tried it with the 1.14 and 1.14 + 1.14 hotfix.

**Comment by TheoKah** [comment]
Have you tried forcing a default currency with /cs config currency ?

I'll fix this bug asap

**Comment by ratquaza** [comment]
Ill try that now and see if that fixes anything.

**Comment by ratquaza** [comment]
That seemed to fix it, thank you!

**Comment by TheoKah** [comment]
Fixed by https://github.com/TheoKah/CarrotShop/commit/ef491679adfa95694758a49c4fd800fac37feda5

I'll publish this in a few. Adding 3 new signs

**Comment by TheoKah** [comment]
Here you go: https://github.com/TheoKah/CarrotShop/releases/tag/1.15

**Comment by ratquaza** [comment]
Thanks! Also, what is the difference between the "i" signs and "a" signs?

**Comment by TheoKah** [comment]
Check the wiki :p

i is for infinite: will create items
a is for admin: still need a chest with items but not linked to a player so infinite money
