### ISSUE TITLE
Sponge api 7

### ISSUE THREAD

**Issue by ghost** [TheoKah/CarrotShop#20]
Please update to sponge api 7

**Comment by TheoKah** [comment]
[CarrotShop-1.15-S7.0-MC1.12.2.tar.gz](https://github.com/TheoKah/CarrotShop/files/1424398/CarrotShop-1.15-S7.0-MC1.12.2.tar.gz)

Here it is. I'll officialise it asap. (DeviceOn, Off and toggle disabled in this version for now. The rest is working.

**Comment by ghost** [comment]
Thx a lot!
