### ISSUE TITLE
Buy Option Not working API 7 

### ISSUE THREAD

**Issue by BenOverBich** [TheoKah/CarrotShop#21]
Hi I am Using this Plugin with 
Total Economy 1.7.1

I set up the shops properly but when someone tries to buy something it just asks them if they want to buy it but wont actually let them.

Selling seems to work fine but Buying is currently my issues, am I doing something wrong?

Also Is there a way you can add instructions on the actual help command and not just a link to the wiki..

**Comment by TheoKah** [comment]
What version are you using? Do you have an error in the console?

About the help message, I like it that way because it's easier to maintain. Now I'm open to discussion.

**Comment by BenOverBich** [comment]
Im using version 1.15 the latest. with Sponge Experimental for 1.12.2 and Forge 2503 Everything else works except for the buy option it just keeps repeating the question.

And No errors in regard to the Shop in the log

**Comment by TheoKah** [comment]
You got it from the "release" tab or from #20 ?

**Comment by BenOverBich** [comment]
I got it from the release tab. The #20 link doesn't seem to be a .jar

**Comment by BenOverBich** [comment]
Any Qay you can update the release tab with the wroming version. The Bersiom you uploaded seems to be a 1kb Jar file compressed with Linux based Zip format. I honestly am not skilled enough to figure put what to do with that file on #20 so A standard 
Jar  updated package would be awesome

**Comment by TheoKah** [comment]
From linux use `unzip file.zip`, from windows: right click and go 'extract all...'

You will get the .jar to use

**Comment by Kosyne** [comment]
I can confirm that that link doesn't work for me either. The jar file is only 1kb, as opposed to say 1.15's 95kb. The jar itself only contains a singular file `CarrotShop-1.15-S7.0-MC1.12.2` which is 10kb of padding.

**Comment by TheoKah** [comment]
Ok wierd. I'll add the .jar to the release tab in 20 mins when I have a computer

**Comment by TheoKah** [comment]
Should be good. You can get it from the release tab.
Let me know how it goes

**Comment by Kosyne** [comment]
Did a quick test at my item exchange kiosk (iBuy and iSell of gold to/from TE currency), and works just fine. Thanks for the quick update!

**Comment by BenOverBich** [comment]
Confirmed Working with the Release download. Thanks for updating this. Closing Issue
