### ISSUE TITLE
Can't buy stuff.

### ISSUE THREAD

**Issue by TheIdioticOtaku** [TheoKah/CarrotShop#22]
Hello, I just got sponge and this plugin along with a few others. When I click on the sign it pops up 'Would you like to buy' but I'm not sure how to actually purchase things?
PS: This could possibly be because I am having issues with my economy plugin currently. 
![shopissue](https://user-images.githubusercontent.com/33495197/32604479-61c5c77c-c513-11e7-8082-4f1523d69748.png)

**Comment by yepidoodles** [comment]
Left click gives info on the shop, right click actually buys it. Looks like you're left clicking only.

**Comment by TheIdioticOtaku** [comment]
Nothing happens when I right click.

**Comment by TheoKah** [comment]
What version of minecraft, sponge, and plugin do you have?

**Comment by TheIdioticOtaku** [comment]
Version 1.12.2 Minecraft, 1.12.2 Sponge, and version 1.15 of the plugin.

**Comment by TheoKah** [comment]
Make sure you are using 'CarrotShop-1.15-S7.0-MC1.12.2.jar' from the release tab

**Comment by TheIdioticOtaku** [comment]
Okay, thanks! That's probably the issue. I'll go download that and let you know how it works. :)

**Comment by TheIdioticOtaku** [comment]
On the Versions page I'm only seeing the version  I currently have installed which is just 1.15.jar

**Comment by TheoKah** [comment]
https://github.com/TheoKah/CarrotShop/releases/tag/1.15

**Comment by TheIdioticOtaku** [comment]
Oh, thank you! Downloading it now. :)

**Comment by TheIdioticOtaku** [comment]
Its working now! Yay! Thank you!
