### ISSUE TITLE
could not set up shops,a exception thrown while click at a sign after click a chest.

### ISSUE THREAD

**Issue by Tollainmear** [TheoKah/CarrotShop#25]
see exception report at gist:
https://gist.github.com/Tollainmear/5beb507f7c9aa8b5594c740b9331dede#file-gistfile1-txt

while i create a shop(while i hold a redstonedust to click at a sign),the exception thrown.

**Comment by Tollainmear** [comment]
btw may i transport this nice plugin to chinese minecraft forum 'MCBBS'?

**Comment by TheoKah** [comment]
Hi,

You can transport it. I'll make an translatable version in january.

About your problem. Do you have a currency plugin installed?

**Comment by Tollainmear** [comment]
thanks for your reply，i've test this latest version at my localhost server and i forget to install the currency plugin,that's my mistake.

I have post Carrot-Shop at [HERE](http://www.mcbbs.net/thread-772777-1-1.html) with links to your git repo,and i also leave a link to make users could only download CS. from your ore page.

    : )

**Comment by Tollainmear** [comment]
Hi~ when could we get the translatable version?

**Comment by TheoKah** [comment]
Sure. I'll work on this asap.

**Comment by TheoKah** [comment]
Language is supported on 1.16
You will have a language.conf file created in the config folder on 1st run

Edit it then restart the server or type `/cs config reload`

Feel free to send me your translation

**Comment by Tollainmear** [comment]
Fin, I'm going to deal with it~

**Comment by Tollainmear** [comment]
I have already translated the language file, I found two problems with CarrotShop:
1.CarrotShop dont have config file, how could we choose the language file?
2.Could you describe what is "PRICE_TRANSLATION_HINTS" ? I dont understand.
😀

**Comment by TheoKah** [comment]
You can modify the language file you find in the config folder directly.
Maybe you wanted each player to be able to use a different language? If that is the case, it is not possible but would be a nice feature. I can make that hapen

The price hint is not used. It is just to inform the translators of the available placeholders for the price format

**Comment by Tollainmear** [comment]
[language.zip](https://github.com/TheoKah/CarrotShop/files/1691799/language.zip)


OK, and Im not mean that, the word 'we' in 1st problem means us server owners, it seem like no config file to make Chinese server owners choose the Chinese language file. So maybe we could just replace the language file with which is translated. however, I think its dosent matter~ thanks for updating carrotshop! here is the translated language file in Chinese, and you can use this anywhere~

BTW, I have transport CS to MCBBS with a detailed tutorial in Chinese, considering there some server owners was not good at English (just like me haha), you could add that Link to '/carrotshop help' to guide Chinese users to lean this plugins

**Comment by TheoKah** [comment]
Yes. Just change the file and restart or type /cs config reload

I'll add your translation to the repository.

About the link in `/cs help` I can add a translation string for the help url. This way any owner can use his own link.

**Comment by Tollainmear** [comment]
Cool, I'm glade to see that~~ 😆

**Comment by TheoKah** [comment]
This is now possible with 1.17 if you edit `WIKI_URL` in language file
