### ISSUE TITLE
Can users profit from [DeviceOn]/[DeviceOff]/[Toggle] ?

### ISSUE THREAD

**Issue by InflamedSebi** [TheoKah/CarrotShop#27]
So is there a way to let users receive the money others spent at their sign?
Seems like the money is just being taken away.

**Comment by TheoKah** [comment]
Sure thing. I'll see if I can do that this we

**Comment by TheoKah** [comment]
This is not fixed in 1.17:
- `[DeviceOn]`, `[DeviceOff]` and `[Toggle]` now give money to owners
- `[aDeviceOn]`, `[aDeviceOff]` and `[aToggle]` are for admins only and not linked to an owner

Existing signs will need to be re-created for them to work correctly
