### ISSUE TITLE
Unable to setup iTrade sign

### ISSUE THREAD

**Issue by flamechair** [TheoKah/CarrotShop#28]
Hi,

I'm trying to setup an iTrade sign, I'm following these steps:

1. Place down 2 chests
2. Put contents to trade for and get in their respective chest
3. Put a sign that hast [iTrade] on line 1
4. Punch both chests with redstone, then the sign
5. Get an error saying that iTrade signs require 2 chests.

Am I doing this wrong? I looked on the wiki and it said nothing specifically about Trade signs, so not sure how to proceed.

**Comment by TheoKah** [comment]
When you left click a chest with redstore, check the message in chat. If will tell you if the location is stored or removed.

**Comment by flamechair** [comment]
Yes, it reports as stored. I click both chests, and both times the location is marked as "stored". Then when I click the sign it says that it requires 2 chests.

**Comment by TheoKah** [comment]
What version of sponge and plugin are you on?
What kind of chest is it?

Does aTrade and Trade signs work?

**Comment by flamechair** [comment]
spongeforge-1.12.2-2611-7.1.0-BETA-2942
CarrotShop-1.17-S7.0-MC1.12.2

Both chests are Oak chests (non-trapped)

aTrade signs do not work
Trade signs do not work

They all say the same thing "X requires two chests"

![2018-03-03_14 39 32](https://user-images.githubusercontent.com/8901422/36939071-c3a3a018-1ef0-11e8-97fa-195f52da9fe0.png)

**Comment by TheoKah** [comment]
I'll try to reproduce using the same sponge version tomorrow

**Comment by flamechair** [comment]
Further testing shows that a player can create a sign shop, but I (admin) cannot. This might be a permissions issue. I can confirm that the player group has permissions to create shops, and the admin group inherits permissions from the player group, so it shouldn't be an issue.

**Comment by TheoKah** [comment]
Players can make a trade sign?

**Comment by flamechair** [comment]
Yes, they can

**Comment by TheoKah** [comment]
Sorry for late answer.
If this still a problem?

If it is, you can contact me on discord: https://discord.gg/3ZSt2cq
