### ISSUE TITLE
[BUG]Could not parse the price with floating number

### ISSUE THREAD

**Issue by Tollainmear** [TheoKah/CarrotShop#29]
If set a sign which assigned a number with floating number at 4th line, the shop will with wrong price setup.

![qq 20180321134921](https://user-images.githubusercontent.com/25898067/37696134-59368bf0-2d0f-11e8-8476-e6d182d0cd0b.png)

using the latest version of Carrotshop in Spongeapi7.

**Comment by TheoKah** [comment]
Hi,

I'll see what can be done.
Note that I cannot accept your PR as it is because it changes the color of the sign even when no shop is actually created.

**Comment by Tollainmear** [comment]
fine, it's dosen't matter, I have noticed that you are using the integer variable to store the price, so to solve it, I tried to change those variables to `float`

**Comment by TheoKah** [comment]
Hi. I added support for floating numbers. This will be available in the next release later today or tomorrow
