### ISSUE TITLE
iSell Problem

### ISSUE THREAD

**Issue by kobaloi147** [TheoKah/CarrotShop#3]
I don't know if it's just me or not but I don't see anywhere anything about a permission node to be able to sell to this type of shop. Is this just me being stupid or is this a problem with the plugin? I can sell just fine when I have full permissions to every plugin but when I go to the default rank to test it I can no longer sell the items.

**Comment by TheoKah** [comment]
Buy, sell and trade signs need no special perms.
ibuy, isell and itrade need the perm node carrotshop.admin

Also, make sure you have an economy plugin installed. Without an economy plugin, only trade and itrade works

**Comment by kobaloi147** [comment]
Well without having the carrotshop.admin node I can buy the items from an iBuy shop, just not sell them??

**Comment by TheoKah** [comment]
Anyone can USE the sign, the perm node is required to SETUP the i-signs

**Comment by kobaloi147** [comment]
Yea that's what I mean, when I set up the shop it says it's set up, but it doesn't allow anyone to sell the items to the shop, they can only buy items.

**Comment by kobaloi147** [comment]
Could the problem be that I'm using Sponge/Spongeforge api 6.0.0?

**Comment by TheoKah** [comment]
Yes, this could be the problem indeed. I'll work on this tomorrow

**Comment by kobaloi147** [comment]
Okay, no rush on it, but thank you so much.

**Comment by dobertthenerd** [comment]
I am having this issue also
