### ISSUE TITLE
[Bug with GP] On player sold blocks

### ISSUE THREAD

**Issue by Tollainmear** [TheoKah/CarrotShop#30]
as we know, GriefPrevention has a protection to prevent strangers build block in a personal claim, that appears if a  stranger place a block, GP cancel it and return the block to him.

The bug is if the customer doesn't have claims permission to place blocks when he sell block with shifting mode（sneak）, the sold block action (right interact the sign) would be regard as place event by GP, so GP prevent placing event and give block back to the customer while doesn't cancel the sell event. so customer will earn money by none block paid.

**Comment by TheoKah** [comment]
Has this problem been reported to GP?
It looks like GP is the one that duplicates the item by giving it back.

Only allowing use of signs with empty hand is not acceptable.

I would gladly lower the Listener from "AFTER_PRE" to "FIRST" and cancel the event. But this might cause problem with people not being able to use the signs in claimed areas.

**Comment by Tollainmear** [comment]
so just check if the player's hand was not empty.

**Comment by TheoKah** [comment]
I do not want to restrict shop use to empty hand.

Have you reported this to GP? I'm happy changing a few things if needed, as long as it doesn't change the gameplay

I'll close in this issue in the meantime.

**Comment by TheoKah** [comment]
Actually I'm adding a config option to enforce empty hand when using signs. (default to false)

Will be in next release later today or tomorrow
