### ISSUE TITLE
Shop Signs reset with every reboot

### ISSUE THREAD

**Issue by WaterMonitor** [TheoKah/CarrotShop#32]
I recently moved my shop to a new world and I am able to create sign shops in the world but as soon as the server restarts all signs in that world just reset. 

Carrotshop Version: CarrotShop-1.17-S7.0-MC1.12.2
Sponge Version: spongeforge-1.12.2-2611-7.1.0-BETA-2931
Error log: https://pastebin.com/JnqbygdD

Note: Signs still function in other worlds on the same server

**Comment by TheoKah** [comment]
Sorry to hear that.

```
InvalidDataException: Could not find world by UUID: 2fb6bdff-f4db-4947-9252-9d9fe1059e68
```

How did you create this world?

**Comment by TheoKah** [comment]
Closing as there is no answer.
Feel free to reopen if you still need help with this
