### ISSUE TITLE
Taxes

### ISSUE THREAD

**Issue by Shybella** [TheoKah/CarrotShop#35]
Tax system on shops would be awesome and the ability to funnel the tax money into a eco account.

**Comment by TheoKah** [comment]
You mean like admin taxes serverwide?

What do you have in mind?

I can add that as a toglable feature. Where would the money go? To a player? To a virtual account? How would the money be accessed?

**Comment by Shybella** [comment]
Tax the player a percentage on buying an item from a sign shop.
The tax money goes into a virtual account. 

Have the tax system on toggle.
Have the percentage modifiable.

Sales tax should be plenty.

**Comment by Shybella** [comment]
This would be such a neat addition

**Comment by Steve505** [comment]
Totally agree! Wanna see this function on our technic server!

**Comment by heginbotham1** [comment]
Taxing would be a good function to add to this plugin so we will be able to charge players additional funds.

**Comment by TheoKah** [comment]
I'll see it I can add that on saturday. It is an easy one.

**Comment by TheoKah** [comment]
Taxes will be available in next release. Later today or tomorrow

**Comment by Shybella** [comment]
Thanks, tested and is working.

Although, is the funds transferred to a virtual account?

**Comment by TheoKah** [comment]
Not yet. I plan to add that on next release.
