### ISSUE TITLE
I can only buy all items in the chest...

### ISSUE THREAD

**Issue by ronangamero** [TheoKah/CarrotShop#36]
How do I make the chest sell one item at the time? it only sells me all items there.

**Comment by yepidoodles** [comment]
When you link the chest, only put in the chest the amount you want to sell. You can then stock it afterwards.

**Comment by ronangamero** [comment]
Oh damn... this will be so hard to explain to players... it will not work for our server. it'd be waaay easier if the 2nd line on the sign was the quantity...

**Comment by yepidoodles** [comment]
I have a youtube tutorial that I made for it if you'd like a link, and if that's okay with @TheoKah , although I do kinda advertise my own servers on it.

**Comment by TheoKah** [comment]
Sure. You can link the video :)

**Comment by yepidoodles** [comment]
https://www.youtube.com/watch?v=evnbshoQ8u8

I made it last year, but the plugin hasn't changed much since then, so it's still applicable.
