### ISSUE TITLE
IT worked now it doesnt

### ISSUE THREAD

**Issue by FunyDucky** [TheoKah/CarrotShop#37]
this plugin did work for me then out of no where when I click on the sign it doesnt give me anything, it says i purchased the item but my balance is the same so is my invatory it didnt give me anything, please help I tryed using diffrent Carrot shop verzions but it still didnt work !please!

**Comment by TheoKah** [comment]
What version of minectaft, sponge and plugin are you using?

**Comment by TheoKah** [comment]
I'll close the ticket as you did not answer.

If you still have the problem you can join https://discord.gg/3ZSt2cq for quick help
