### ISSUE TITLE
No on is able to create simple [Buy] shop

### ISSUE THREAD

**Issue by UniversalSoul** [TheoKah/CarrotShop#38]
On our server no one except those with the * permission are able to make normal [Buy] shops. They can make [Sell] and [Trade] but not [Buy]. I tried giving them the "carrotshop.create.buy" permission but they still can't do it. One of our Admins even gave themselves carrotshop.* and they can create every other shop but not [Buy].

**Comment by TheoKah** [comment]
Do you have a message in chat or in console when trying to create a sign?
Do you have an economy plugin installed?

**Comment by UniversalSoul** [comment]
http://prntscr.com/k6iwpi
We do not have an economy plugin installed.

**Comment by TheoKah** [comment]
Buy and sell signs are disabled when there is no economy plugin installed because they need it to operate.

The message you see must come a protection plugin or somewhere else.
