### ISSUE TITLE
AdminShop Migration Integration

### ISSUE THREAD

**Issue by SjsolisZXA** [TheoKah/CarrotShop#41]
Hello, I'd like to know if this plugin can provide a migration feature for those of us who used other admin shop like plugins like [AdminShop](https://forums.spongepowered.org/t/adminshop-v1-8-2-server-shops/8867).

**Comment by TheoKah** [comment]
I looked at it. I'm able to extract the info

Note that I will need to override the sign content
Looks like AdminShop let you put anything you want on the sign.
I have to enforce the first line to `[iBuy]` or `[iSell]` and the last one to the price.
I'm wondering if I should let the 2nd and 3rd as-is or enforce them as well to the name and quantity...

**Comment by SjsolisZXA** [comment]
Sounds great! Overriding the signs sounds fine with me. The 1st and 4th line enforcement format is understandable. If the migrating functionality is integrated, I can manually edit the existing signs with SignEdit to fit your format.

If the name of the item could be automatically entered on the second line, it would be great, but I can see how that can be problematic if the name of the item is too long and it can not fit on that same line. In those cases I've used the 4th line to finish naming the item, but that would not leave any room for quantity integers, if the user so chooses to put that in. I think leaving those two spaces as fill in the blanks would be best.  

Additionally, is there a way to have the shop setup so the chest placement isn't necessary when creating an infinite shop?

**Comment by TheoKah** [comment]
I finished this.
The import command will be available in next release (either today or tomorrow)
