### ISSUE TITLE
Carrot Shop report provides nothing...

### ISSUE THREAD

**Issue by liampearson96** [TheoKah/CarrotShop#43]
spongeforge-1.12.2-2705-7.1.0-BETA-3417
CarrotShop-1.17-S7.0-MC1.12.2
FoolCraft 3 modpack

Upon trying to run /carrotshop report it shows nothing but this error in the console:

17:06:48  [Error] [carrotshop]: ERROR: Server returned HTTP response code: 400 for URL: https://carrotshop-ffb97.firebaseio.com/shop.json.
17:06:48  [Error] [carrotshop]: Bad Request.

Also with /carrotshop serverreport:

17:07:50  [Error] [carrotshop]: ERROR: Server returned HTTP response code: 400 for URL: https://carrotshop-ffb97.firebaseio.com/shop.json.
17:07:50  [Error] [carrotshop]: Bad Request.

Thank you

**Comment by TheoKah** [comment]
Hi,

Thank you. I'll see what is hapening on google's side.

**Comment by liampearson96** [comment]
Cheers Pal!

**Comment by TheoKah** [comment]
I see a few entries.
What is the name of your currency?

Can the server access the internet?

**Comment by TheoKah** [comment]
You can reach me for help here: https://discord.gg/3ZSt2cq
