### ISSUE TITLE
[Feature] Tax for creating a shop

### ISSUE THREAD

**Issue by Steve505** [TheoKah/CarrotShop#44]
Hey there!
I was just wondering, if there could be an option to set a "tax" for new created shops (or just tax for every pairing via Redstone).

**Comment by TheoKah** [comment]
I'll add both on saturday.
A price to setup each type of sign + a %age on each purchase.

All default to 0

**Comment by Steve505** [comment]
Fantastic! Thanks for quick response!
Just quick question... Will it be on 1.10.2 version?

**Comment by TheoKah** [comment]
1.10 & 1.12

**Comment by TheoKah** [comment]
I finished the feature. Will be available in next release, later today or tomorrow
