### ISSUE TITLE
Dynamic iBuy/iSell Scaling

### ISSUE THREAD

**Issue by Shybella** [TheoKah/CarrotShop#45]
You would need to track purchase rate/time(m,h,d) to get a base value to work on scaling prices on iBuy/iSell signs dynamically. 

The higher the purchase rate an hour(10/hour) each 1 increment value equals a configurable percentage the sign price will either decrease (-10/hour or increase (10/hour) from their previous value.

This would be a advanced feature but opens the door to so many new market strategies for player shops working against Admin Shop pricing.

**Comment by TheoKah** [comment]
Tell me more. Can you give me a concrete example?

I plan to work on the plugin this week end

**Comment by Shybella** [comment]
Ex: 1 bought/sold item = 0.1% increase/decrease to current price.

If 10 units of Diamond are bought from a [iBuy] sign. Every x amount of time passed (Ex: 1h) and total units bought equal 10 as an example. The price on the Diamond [iBuy] sign after the 1 hour period timer has passed runs a task that adds items-sold(10) x 0.1% = 1.0%. The current prices gets increased 1.0% of its current price or default initial price.

10 items sold would increase the current price by 1.0% So, if the Diamond costs 100 and 10 untils sold in that hour. The price would increase to 101 up from 100.

If no units are sold within that hour it resets back to the default initial price OR previous price unless previous price was default initial price.

The same concept would be applied for [iSell] signs but instead of increasing the default initial price or current price, it decreases. If non sold set back to default initial price or previous price.

Opinion:
- Percentage needs to be modifiable.
- Rate at when the task runs needs to be modifiable.

Ex: `1h = 0.0001` or 0.1% for each time sold
OR
Ex: `items_sold/bought_regardless_of_time_passed = 0.0001` or 0.1%. 0.1% gets added regardless of time, the amount of time passed when task runs to update [iBuy] or [iSell] signs does not matter. The units sold/bought within that time is the only thing that matters.

The amount of new tactics and strategies If this was implemented correctly would open a whole new can of worms when it comes to competition and market manipulation.

**Comment by Shybella** [comment]
The amount of new tactics and strategies If this was implemented correctly would open a whole new can of worms when it comes to competition and market manipulation.

**Comment by Shybella** [comment]
In sense, this would be taking control of a already existent supply and demand system but _regulating_ it based on _volumetric_ traffic from items sold/bought.

**Comment by TheoKah** [comment]
I like the idea.
Obviously this would be a new sign type, like [sBuy] and [sSell] (s for stock)
I'm open to name ideas.

Note that this will require to overwrite the price line on the sign.
I might not be able to do that this week as I want to work on other issues and features first, like an auto-link feature with no redstone if a sign is placed directly on a chest; or the tax system,

**Comment by Shybella** [comment]
Came up with a neat idea when this becomes something.

You could take https://ore.spongepowered.org/pie_flavor/Pieconomy and as an example make a gold ingot have a value. That value can be traded for currency via a "stock/scaling" carrot shot sign. You'd have the real value but depending on the market at the time, it could either be worth more or less.

**Comment by Shybella** [comment]
https://ore.spongepowered.org/Rojo_McDerp/Dynamic-Shops
