### ISSUE TITLE
Discrepancies on what is being sold

### ISSUE THREAD

**Issue by Willynator** [TheoKah/CarrotShop#47]
https://gyazo.com/103d2fe3ec55bd8ae5d8e641363e5b2a

I believe this in itself can be a huge issue, perhaps 1 line should be kept to make sure the correct item is being sold as this is a potential source to scam players and can leave this plugin unviable for servers with larger player counts.

**Comment by yepidoodles** [comment]
This is a matter of opinion; The names of items, especially modded items, are usually wrong - the data usually used in these kind of plugins are not the names you see on the item names. Plus, there is the added problem of specialised items and amounts, and the fact that you can have more than one type of item in a chest when selling things.

If you are worried about players being scammed, just make sure your players are aware to left click the sign before using right click to buy - it shows what is in it (although using the crappy names I mentioned before).

**Comment by Willynator** [comment]
My complaint stems from the fact anyone can write anything to say something else will be sold.

It generally is also a good idea to assume ignorance from the perspective of players

Also in terms of modded items it would be assumed they take the name such as pixelmon:masterball or it can remove the source and place the name after

Shop plugins in spigot generally handle stuff in such a manner and if need be add a #nbt type of thing
In which case a second sign may be added for specification. It also is much less likely to be a scam if an item being sold holds NBT data or is enchanted

**Comment by TheoKah** [comment]
If you put your mouse over the item in chat you should be able to see the exact type.

As yepi said, it can be hard to get what will eventually be displayed. Using this method happen to be the most accurate.

If you want, you can alter the language file to add an extra 'mouse over item for details'

**Comment by TheoKah** [comment]
Closing this issue as for now as I think hovering over the item name in chat for more details is enough.
Feel free to re-open if you want to discuss it
