### ISSUE TITLE
Where is stored information of chest?

### ISSUE THREAD

**Issue by superwizzman** [TheoKah/CarrotShop#48]
Hi, I had a little problem with my server and my mods. An update of aether mod and orbis API affect somethings I do a /fml confirm. But, since I did this, the shops of my players don't works. So where is stored the files of the list of shops? I whould copy this file of my backup. 

Thank you!

**Comment by TheoKah** [comment]
Hi

Default location is the config folder of the plugins atm

**Comment by superwizzman** [comment]
Hi I found tank you. But I was able to repair just one shop... I will check that. :/
