### ISSUE TITLE
Shop can't handle stacks correctly

### ISSUE THREAD

**Issue by winnetrie83** [TheoKah/CarrotShop#5]
If you set up a shop where people can buy 5 stones for 1 dollar and the shop does not have stacks of 5 stones it says the shop is empty. So this means the shop has been set that people can buy 5 stones for 1 dollar and the shop has multiple stacks of 64 stones and someone wants to buy it, the shop will tell you it is empty (because it does not have a stack of 5 stones). The same thing happens for a shop where you can sell things.

**Comment by TheoKah** [comment]
What version of minecraft and sponge are you using?

**Comment by winnetrie83** [comment]
spongeforge-1.11.2-2282-6.1.0-BETA-2352
MC 1.11.2
Also forge-1.11.2-13.20.0.2304

**Comment by TheoKah** [comment]
that's why, this version is for 1.10.2 / sponge api 5.1.0

Here is an experimental version compiled with api 6, let me know if it works
[CarrotShop-1.5-6.0.0-EXPERIMENTAL.zip](https://github.com/TheoKah/CarrotShop/files/1034540/CarrotShop-1.5-6.0.0-EXPERIMENTAL.zip)

(note this is the dev version so I included your sugestion 1 as I 'm just done coding it )

**Comment by winnetrie83** [comment]
oh it was for 1.10. I'm sorry didn't see that. I test it right away!! Thank you!

**Comment by TheoKah** [comment]
I'll provide official support for api 6 and 7 soon, for now, that's just 5
api 6 is now unsupported by sponge, and api 7 is experimental :/

**Comment by winnetrie83** [comment]
Are you aware that it is a zip file? It appears the plugin does not load. Testing it right now and seems not to be present

**Comment by TheoKah** [comment]
yes, you need to unzip it. github does not allow .jar in the replies

**Comment by winnetrie83** [comment]
Aha! Thanks, didn't know that.

**Comment by winnetrie83** [comment]
The problem is still there. The chest where i can buy stuff is filled with 10 stacks of 64 redwool, yet it says the shop is empty. When i turn all the stacks into stacks of 1, i can buy stuff.

**Comment by TheoKah** [comment]
Then this mean I'll have to look into it a bit further. Something changed between api 5 and 6
I'll see what I can do.

**Comment by TheoKah** [comment]
I changed a couple things in v1.5 do you still have problem with sponge 1.11.2 ?

**Comment by TheoKah** [comment]
No answer after 1 month. Closing.

Feel free to reopen if problem is still there
