### ISSUE TITLE
once translated into German^^

### ISSUE THREAD

**Issue by xXjojojXx** [TheoKah/CarrotShop#50]
German
                                             language.conf
-------------------------------------------------------------------------------------------------------------------

"CMD_CONFIG_CURRENCY"="Standart Währung ist %name% (%id)"
"CMD_CONFIG_RELOAD"="Config neu geladen"
"CMD_CONFIG_RELOAD_FILE"="Konnte die Konfigurationsdatei nicht laden oder erstellen"
"CMD_IMPORT_ADMINSHOP_ERROR_FILE"="Die AdminShop Shop-Datendatei kann nicht gefunden oder geöffnet werden"
"CMD_IMPORT_ADMINSHOP_ERROR_LOAD"="Fehler beim Laden der AdminShop Shop-Datendatei"
"CMD_IMPORT_ADMINSHOP_ERROR_LOAD_ITEM"="Fehler beim Laden des AdminShop-Shop-Datenelements"
"CMD_IMPORT_USAGE"="Sie benötigen einen der folgenden Parameter:"
"CMD_SPAM"="Shop-Nutzungsbericht: %status%"
"CONSOLE_ERROR_GENERIC"="Fehler: %error%"
"CONSOLE_ERROR_LOAD"="Beim Laden von CarrotShops sind Fehler aufgetreten"
"CONSOLE_ERROR_LOGS"="Speichern von Protokollen für den Shop %owner% nicht möglich, ausgelöst durch %source%: %error%"
"CONSOLE_ERROR_PLAYER"="Muss ein Spieler sein"
"CURRENCY_SERVER"="Shop-Währung entsprechend der Serverkonfiguration"
"CURRENCY_VALUE"="Shopwährung eingestellt auf %name%"
"HELP_DESC_CMD_CONFIG"="Change or reload config of the plugin"
"HELP_DESC_CMD_CONFIG_CURRENCY"="Get/Set the default currency"
"HELP_DESC_CMD_CONFIG_RELOAD"="Reload the language file"
"HELP_DESC_CMD_IMPORT"="Import shop data from another plugin"
"HELP_DESC_CMD_MAIN"="Hauptbefehl CarrotShop"
"HELP_DESC_CMD_OREPORT"="Generiert einen CarrotShop-Bericht für einen anderen Spieler"
"HELP_DESC_CMD_REPORT"="Generiert einen CarrotShop-Bericht"
"HELP_DESC_CMD_SPAM"="Shopnachricht umschalten, wenn jemand Ihren Shop verwendet"
"HELP_DESC_CMD_SREPORT"="Generiert einen CarrotShop-Bericht für iSigns"
"HELP_DESC_CMD_WIKI"="Zeigt einen Link zum Shop-Wiki an"
"HELP_HEADER_CMD_CONFIG"="/carrotshop config"
"HELP_HEADER_CMD_MAIN"="/carrotshop"
"LOCATION_REMOVED"="Standort des Elements entfernt"
"LOCATION_STORED"="Speicherort des Artikels"
"PRICE_DEFAULT"="%value% %currencyFullPlural%"
"PRICE_ONE"="%value% %currencyFull%"
"PRICE_TRANSLATION_HINTS"="Akzeptierte Platzhalter für PRICE_*: %value% %currencyFull% %currencyFullPlural% %currencySymbol%"
"PRICE_ZERO"=nothing
"REPORT_ERROR_DATA"="Es wurden keine Daten zum Generieren eines Berichts gefunden"
"REPORT_ERROR_OPERM"="Sie haben keine Berechtigung, Berichte für andere Spieler zu erstellen"
"REPORT_ERROR_PERM"="Sie haben keine Berechtigung zum Erstellen von Berichten"
"REPORT_PREPARE"="Der Bericht wird vorbereitet ..."
"REPORT_READY"="Bericht ist fertig: %url%"
"SHOP_BANK"="Dein Kontostand: %bank%"
"SHOP_BANK_HELP"="Klicken Sie mit der rechten Maustaste, um Ihr Guthaben zu sehen"
"SHOP_CHEST"="%type% Schild erfordert eine Truhe"
"SHOP_CHEST2"="%type% Schild erfordert zwei Truhe"
"SHOP_CHEST_EMPTY"="Truhe kann nicht leer sein"
"SHOP_COST"="Sie haben nicht genug Geld, um den Shop zu erstellen. Ein %type% Shop kostet %cost%"
"SHOP_CURRENCY"="Dieses Schild verwendet die Standardwährung: %name%"
"SHOP_CURRENCY_LOOP"="Klicken Sie mit der linken Maustaste auf das Schild, um eine andere Währung zu verwenden"
"SHOP_DEVICEOFF"="Gerät deaktiviert für %price%"
"SHOP_DEVICEOFF_HELP"="Deaktivieren für %price%?"
"SHOP_DEVICEOFF_HELP_NOECON"="Deaktivieren?"
"SHOP_DEVICEOFF_NOECON"="Gerät deaktiviert"
"SHOP_DEVICEON"="Gerät aktiviert für %price%"
"SHOP_DEVICEON_HELP"="aktivieren für %price%?"
"SHOP_DEVICEON_HELP_NOECON"="Aktivieren?"
"SHOP_DEVICEON_NOECON"="Gerät aktiviert"
"SHOP_DEVICE_OTHER"="%player% benutzt dein [%type%] Zeichen für %price%"
"SHOP_DEVICE_OTHER_NOECON"="%player% benutzt dein [%type%] Zeichen"
"SHOP_DEVICE_OTHER_TAX"="%player% benutzt dein [%type%] Zeichen für %price%. Mit %tax%% tax bekommst du %tprice%"
"SHOP_DONE"="Sie haben ein Shop [%type%] eingerichtet:"
"SHOP_DONE_COST"="Sie haben ein Shop [%type%] eingerichtet für %cost%:"
"SHOP_EMPTY"="Dieser Shop ist leer!"
"SHOP_EMPTYHAND"="Sie dürfen nur Geschäfte mit leeren Händen verwenden"
"SHOP_ERROR_MONEY"="Kann Ihnen das Geld nicht geben!"
"SHOP_FORMAT_BUY"="Kaufe %items% für %price%?"
"SHOP_FORMAT_SELL"="Verkaufe %items% für %price%?"
"SHOP_FORMAT_TRADE"="Tausche %items% und bekomme %items%?"
"SHOP_FULL"="Dieser Shop ist voll!"
"SHOP_HEAL"="Du hast für %price% geheilt"
"SHOP_HEAL_HELP"="Heilen für %price%?"
"SHOP_HEAL_HELP_NOECON"="Heilen?"
"SHOP_HEAL_NOECON"="Geheilt"
"SHOP_ITEMS"="Sie haben die Artikel nicht!"
"SHOP_LEVER"="%type% Schilder erfordern einen Hebel"
"SHOP_MONEY"="Sie haben nicht genug Geld!"
"SHOP_OMONEY"="Ladenbesitzer hat nicht genug Geld!"
"SHOP_OVERRIDE"="Dieser Shop würde einen Shop überschreiben, den Sie nicht besitzen. Abbrechen."
"SHOP_PERM"="Du hast keine Perms, um eine [%type%] Shop zu bauen"
"SHOP_PRICE"="falscher Preis"
"SHOP_RECAP_BUY"="Du kauftest %items% für %price%"
"SHOP_RECAP_OBUY"="%player% kaufte %items% für %price% von dir"
"SHOP_RECAP_OBUY_TAX"="%player% kaufte %items% für %price% von dir. Mit %tax%% tax bekommst du %tprice%"
"SHOP_RECAP_OSELL"="%player% verkaufte %items% für %price% an dich"
"SHOP_RECAP_OSELL_TAX"="%player% verkaufte %items% für %price% an dich. Mit %tax%% tax bekommst du %tprice%"
"SHOP_RECAP_OTRADE"="%player% tauschte %items% für %items%"
"SHOP_RECAP_SELL"="Du hast %items% verkauft für %price%"
"SHOP_RECAP_TRADE"="Du hast %items% getauscht gegen %items%"
"SHOP_SCHRODINGER"="Dieser Shop ist entweder voll oder leer!"
"SHOP_TOGGLE"="Das Gerät wurde 2 Sekunden lang umgeschaltet %price%"
"SHOP_TOGGLE_HELP"="Umschalten für %price%?"
"SHOP_TOGGLE_HELP_NOECON"="Umschalten?"
"SHOP_TOGGLE_NOECON"="Gerät wurde 2 Sekunden lang umgeschaltet"
"SHOP_USED"="Jemand hat in Ihrer Abwesenheit Ihre Geschäftsschilder benutzt. Benutz %cmd% für mehr Informationen"
"STATUS_OFF"=OFF
"STATUS_ON"=ON
"WIKI_LINK"="Link zum Wiki: %url%"
"WIKI_URL"="https://github.com/TheoKah/CarrotShop/wiki/User-Guide"

**Comment by TheoKah** [comment]
Thank you! I'll add this to the repository

**Comment by TheoKah** [comment]
I applied #49 from @i9hdkill as it was sent first
Feel free to send a PR if you want to improve current translation
