### ISSUE TITLE
CarrotShop can't find world

### ISSUE THREAD

**Issue by krisjenner** [TheoKah/CarrotShop#54]
I created a new overworld for players to move to using nucleus /world create -- carrotshop can't find this world and won't load shops

[error](https://gist.github.com/krisjenner/bcd00f5f407ebfedfd0b11eaebd0be2f)

**Comment by krisjenner** [comment]
`/world setloadonstartup true`

^This fixes it

**Comment by TheoKah** [comment]
Makes sense. I'll have to keep that in mind. Thank you! I'll see if I can reproduce and detect it. Would be nice if I can at least print a message in console.
