### ISSUE TITLE
Multiple [Cmd] signs, but only one file

### ISSUE THREAD

**Issue by Warhawker** [TheoKah/CarrotShop#60]
Hi, I have 6 different [Cmd] signs, but only one file to add a command line for the signs. How can I specify a different command, for each of the signs?

**Comment by TheoKah** [comment]
Hi

After you punch a cmd sign with redstone a file is created server side.
Check console for absolute path if needed.

If this is not the case, console should have more details.

Btw files are linked to the location of the sign, not the sign itself.

**Comment by Warhawker** [comment]
Closed with Hotfix 1.19-1
https://github.com/TheoKah/CarrotShop/releases/tag/1.19-hotfix1
