### ISSUE TITLE
cmd shop

### ISSUE THREAD

**Issue by ThePro1604** [TheoKah/CarrotShop#61]
for some reason i created 3 cmd shops and all three of them were saved on the same cmd file how do i separate them to different files so i can set different command for each sign

**Comment by TheoKah** [comment]
Hi,

Have you tried this:
https://github.com/TheoKah/CarrotShop/releases/tag/1.19-hotfix1 

Use this jar and recreate your cmd signs

**Comment by TheoKah** [comment]
I'll consider this issue fixed. Feel free to open a new issue if this is not the case.
