### ISSUE TITLE
[Serious!] Stealing Chest content from others!

### ISSUE THREAD

**Issue by NeariX67** [TheoKah/CarrotShop#64]
Hey. A Modpack Server uses this Plugin which uses a chunk based claiming system.
if you hit a chest that is not yours (even in a area where you cannot build) you can link it with a sign where you can build and steal all the content off the chest.
I attached a representing video below.
https://youtu.be/oGP3VJyrQdw

**Comment by TheoKah** [comment]
What protection plugin are you using?

**Comment by NeariX67** [comment]
Its called ftb utilities mod. Not a plugin.
https://www.curseforge.com/minecraft/mc-mods/ftb-utilities

The server itself is currently developing a plugin that prevents that. (idk more about it)

**Comment by TheoKah** [comment]
CarrotShop being based on sponge api, you will need to use a sponge based protection plugin. Shop plugin cannot know for sure who is the owner of the chest you want to link.

If you really want to stick with ftbu, having your own plugin that links with ftbu might be the best thing to do.

**Comment by TheoKah** [comment]
I'll close this issue because there is no way for me to know who an unlinked chest belongs to.
Protecting the chests is the job of a protection plugin, which CarrotShop it not.

(Note, see #67 for linked chests)

**Comment by NeariX67** [comment]
My suggestion: Do a config option, that only allows signs to be placed right at the chest and not everywhere. Would solve the problem in the most part

**Comment by TheoKah** [comment]
What you describe, prevent click/interaction on *some* chests, is the job of a protection plugin.
I thing some of the plugins work the exact way you described
