### ISSUE TITLE
z coordinates of the Cmd signs dont work

### ISSUE THREAD

**Issue by Mekrip** [TheoKah/CarrotShop#73]
If i place some CMD signs with the same x and y coordinates but different z coordinates, all of them have the same text file, so all cmd signs in the same row have the same commands.
Im using 1.19-S7.1-MC1.12.2

**Comment by TheoKah** [comment]
Hi,

Make sure you are using the latest version: https://github.com/TheoKah/CarrotShop/releases/tag/1.19-hotfix1

**Comment by Mekrip** [comment]
Oh, didnt saw that.
Thank you very much!
