### ISSUE TITLE
1.6 is great but flaw with design...

### ISSUE THREAD

**Issue by aWitch-Doctor** [TheoKah/CarrotShop#8]
So you have added and fixed all the issues so far.. It wasn't until I added it that I realized people can steal from anyone. I have a world called shops, this is where the perms say they can make the shops. any player can go here and place a buy sign with a purchase price of 1 dollar (on the fourth line) then go to any world and select anyone's chest even if it is on a grief prevention claim then tp back to the sign and steal everything from the chest for 1 dollar. Can you make it so the chest must be placed by the same person that made the sign or so that the chest must be within X amount of blocks of the sign in the same world, or even the chest must be below the wall sign?

**Comment by TheoKah** [comment]
I'll fix it right away

**Comment by aWitch-Doctor** [comment]
Thank you so much for all your work on this plugin and the quick turn around for these issues.

**Comment by TheoKah** [comment]
Here is a quickfix, I'll push version 1.8 in a few minutes after I finished with a command revamp and /shop help command that point to [the wiki](https://github.com/TheoKah/CarrotShop/wiki/User-Guide)

[CarrotShop-1.7-quickfix.jar.zip]() (link removed)

**Comment by TheoKah** [comment]
Should be fully fixed on 1.8: https://github.com/TheoKah/CarrotShop/releases/tag/1.8

**Comment by aWitch-Doctor** [comment]
Hmm, i loaded 1.8 and had a player place a chest inside of his claim. I made sure my perms were the same as a normal players (can't override claims or shops). I was able to select his chest and attach it to my sign. I'm not sure if i did something wrong or if it is still not working. I am using sponge vanilla api 5 build 385 and grief prevention 2.3.1.251. I know they aren't the latest versions but I dont have time at the moment to update my test server.

**Comment by TheoKah** [comment]
The redstone thing now has normal priority. I was not able to link chests in claimed area with 0 perms (didn't try with grief prevention but with nation). Can you check the perms again?

**Comment by aWitch-Doctor** [comment]
Sorry I haven't gotten back to you, was working the past few days. I'm not sure what you mean. I have checked the perms and the members have carrotshop.create and basic grief prevention stuff but i dont see anything that would let them do this.

**Comment by TheoKah** [comment]
Sorry, didn't see your answer. I was talking about the protection plugin permissions

**Comment by TheoKah** [comment]
Can you try this version and tell me if it's better: https://github.com/TheoKah/CarrotShop/releases/tag/1.9

**Comment by aWitch-Doctor** [comment]
It appears that the issue is fixed with 1.9. Thank you again for all your work on this. Safe to close this one.

**Comment by TheoKah** [comment]
Glad to hear that. Sorry it took me so long to fix it.
