### ISSUE TITLE
the admins shop are not infinite

### ISSUE THREAD

**Issue by xXjojojXx** [TheoKah/CarrotShop#83]
I have created an admin shop, but unfortunately it is not infinite. Players can buy the empty one. Please rework.

[aBuy] <--- not infinite

**Comment by TheoKah** [comment]
Hi,

Indeed, admin shops `[aShop]` are linked to a chest with finite supplies.
What you want is infinite shop `[iShop]` where you can destroy the chest after you setup it (`[iBuy]`, `[iSell]`, `[iTrade]`...)

**Comment by xXjojojXx** [comment]
I did if I now try to tear off the chest, I immediately fly from the server.

**Comment by xXjojojXx** [comment]
ohh sry  thx^^
