### ISSUE TITLE
Upcoming Signs

### ISSUE THREAD

**Issue by TheoKah** [TheoKah/CarrotShop#9]
I plan to add a lot of signs to SignShop. Feel free to comment and suggest things

TODO: 

- [x] DeviceOn: linked to a lever to turn it on
- [x] DeviceOff: linked to a lever to turn it off
- [x] Toggle: linked to a lever to turn in on, then off a few seconds later
- [x] Bank: display balance
- [x] Heal: Heal the player at a cost
- [x] Command: execute a command on the server

**Comment by ktole1999** [comment]
i just downloaded this for my server and I am really impressed. Keep up the good work.

**Comment by TheoKah** [comment]
I worked on new signs this week end.

I'll release a new version next week end with possibility to link the same chest to multiple signs.

Any other sign ideas?

**Comment by yepidoodles** [comment]
For the command ones, I assume that's as a cost? and would be an Admin tool, so the server would execute it?

**Comment by TheoKah** [comment]
Yes. Would need admin to setup. And will execute at a cost. Price can be 0

**Comment by TheoKah** [comment]
https://github.com/TheoKah/CarrotShop/releases/tag/1.11

I'll do the command one later as I need to work on the web interface for now
